### ISSUE TITLE
还更新么

### ISSUE THREAD

**Issue by v200123** [Gliese129/bililive-record-uploader#4]
问一问，如果会更新就使用这个了

**Comment by Gliese129** [comment]
会的，这个项目是我的python入门项目，很多地方写的不是很规范，使用过程中也发现一些不足，之后会慢慢重构，也有可能会加新功能。不过如果哪天B站修改了上传接口导致bot无法使用的话，估计就不会更新了

**Comment by Gliese129** [comment]
不过最近因为学业会咕一段时间

**Comment by v200123** [comment]
好叻好叻，搭建完了在看看效果如何了
