### ISSUE TITLE
运行遇到问题

### ISSUE THREAD

**Issue by wufeng15226** [Gliese129/bililive-record-uploader#6]
如下：
![屏幕截图 2023-06-11 012400](https://github.com/Gliese129/bililive-uploader/assets/47237320/56242b82-e185-496e-bbdd-d29cf13b200f)

**Comment by Gliese129** [comment]
试试看将run.py 最后一行换成
~~~
app.run(host='0.0.0.0', port=bot_config.port,
            debug=False, access_log=False, single_process=True)
~~~

如果报错app.config找不到相关的key的话直接替换

------------------------
初步判断可能是多线程导致的bug（？）不过根据你提供的日志，bug反而像是出在协程这边。。。

**Comment by wufeng15226** [comment]
修改之后出现了新的错误，看起来 init 函数没有运行
![image](https://github.com/Gliese129/bililive-uploader/assets/47237320/610e7817-bb32-4cf9-ae27-d695c0f8d933)

**Comment by wufeng15226** [comment]
> 试试看将run.py 最后一行换成
> 
> ```
> app.run(host='0.0.0.0', port=bot_config.port,
>             debug=False, access_log=False, single_process=True)
> ```
> 
> 如果报错app.config找不到相关的key的话直接替换
> 
> 初步判断可能是多线程导致的bug（？）不过根据你提供的日志，bug反而像是出在协程这边。。。

直接替换具体是怎么改？

**Comment by Gliese129** [comment]
将app.config.KEY直接对应成value，run.py的init函数内可以找得到初始化值

**Comment by Gliese129** [comment]
不过这个bug应该是哪个包更新后底层逻辑变了导致的，之后我也会尝试修复掉

**Comment by wufeng15226** [comment]
我把 init 函数内的代码移到了 main 中，现在似乎正常运行了🎉，感谢！
还需要观察一段时间
